<a href="https://colab.research.google.com/github/vikrantyadav11234/DL_-_CNN_Practice/blob/main/keras_tuner_hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os, sys
import numpy as np
import pandas as pd
df=pd.read_csv('/content/diabetes.csv')
df.head(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df['Glucose']=np.where(df['Glucose']==0,df['Glucose'].mean(),df['Glucose'])
df['BloodPressure']=np.where(df['BloodPressure']==0,df['BloodPressure'].mean(),df['BloodPressure'])
df['SkinThickness']=np.where(df['SkinThickness']==0,df['SkinThickness'].mean(),df['SkinThickness'])
df['Insulin']=np.where(df['Insulin']==0,df['Insulin'].mean(),df['Insulin'])
df['BMI']=np.where(df['BMI']==0,df['BMI'].mean(),df['BMI'])

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.681605,72.254807,26.606479,118.660163,32.450805,0.471876,33.240885,0.348958
std,3.369578,30.436016,12.115932,9.631241,93.080358,6.875374,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,20.536458,79.799479,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,79.799479,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    float64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    float64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [ ]:
x= df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
# data normalization
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [ ]:
x

array([[ 0.63994726,  0.86527574, -0.0210444 , ...,  0.16725546,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.20598931, -0.51658286, ..., -0.85153454,
        -0.36506078, -0.19067191],
       [ 1.23388019,  2.01597855, -0.68176235, ..., -1.33182125,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 , -0.02240928, -0.0210444 , ..., -0.90975111,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.14197684, -1.01212132, ..., -0.34213954,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.94297153, -0.18622389, ..., -0.29847711,
        -0.47378505, -0.87137393]])

In [ ]:
# Split the data into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train ,y_test= train_test_split(x,y,test_size=0.2, random_state=101)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import *

# How to select number of hidden layers and number of neurons in each hidden layer, optimizer, activation function, droput etc...

In [ ]:
pip install keras-tuner --upgrade

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (24.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.2.2)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

In [ ]:
import keras_tuner as kt

In [ ]:
# optimizer

In [ ]:
from kerastuner import RandomSearch

<ipython-input-16-7efa24979c35>:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  from kerastuner import RandomSearch

In [ ]:

def build_model(hp):
  model=Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))
  optimizer=hp.Choice('optimizer', values=['adam','sgd', 'rmsprop', 'adadelta'])
  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [ ]:
from typing_extensions import Literal
# Best optimezer
tuner= kt.RandomSearch(build_model, objective="val_accuracy")

In [ ]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7662337422370911

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 12s

In [ ]:
tuner.get_best_hyperparameters()

In [ ]:
# Best optimizer
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [ ]:
model=tuner.get_best_models(num_models=1)[0]

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 32)                288

 dense_1 (Dense)             (None, 1)                 33

=================================================================
Total params: 321 (1.25 KB)
Trainable params: 321 (1.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6,
           validation_data=( X_test, y_test), verbose=1)

Epoch 7/100
20/20 [==============================] - 1s 13ms/step - loss: 0.5131 - accuracy: 0.7541 - val_loss: 0.4860 - val_accuracy: 0.7597
Epoch 8/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4996 - accuracy: 0.7508 - val_loss: 0.4732 - val_accuracy: 0.7597
Epoch 9/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4910 - accuracy: 0.7508 - val_loss: 0.4643 - val_accuracy: 0.7727
Epoch 10/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4837 - accuracy: 0.7524 - val_loss: 0.4578 - val_accuracy: 0.7727
Epoch 11/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4784 - accuracy: 0.7557 - val_loss: 0.4511 - val_accuracy: 0.7792
Epoch 12/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4735 - accuracy: 0.7590 - val_loss: 0.4469 - val_accuracy: 0.7727
Epoch 13/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4699 - accuracy: 0.7590 - val_loss: 0.4434 - val_accuracy: 0.7727
Epoch 14/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4667 - accuracy: 0.7606 - val_loss: 0.4406 - val_accuracy: 0.7727
Epoch 15/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4641 - accuracy: 0.7687 - val_loss: 0.4379 - val_accuracy: 0.7727
Epoch 16/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4614 - accuracy: 0.7704 - val_loss: 0.4358 - val_accuracy: 0.7727
Epoch 17/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4597 - accuracy: 0.7720 - val_loss: 0.4357 - val_accuracy: 0.7727
Epoch 18/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4577 - accuracy: 0.7736 - val_loss: 0.4345 - val_accuracy: 0.7727
Epoch 19/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4568 - accuracy: 0.7687 - val_loss: 0.4325 - val_accuracy: 0.7727
Epoch 20/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4553 - accuracy: 0.7671 - val_loss: 0.4309 - val_accuracy: 0.7727
Epoch 21/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4538 - accuracy: 0.7704 - val_loss: 0.4315 - val_accuracy: 0.7727
Epoch 22/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4532 - accuracy: 0.7736 - val_loss: 0.4310 - val_accuracy: 0.7727
Epoch 23/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4516 - accuracy: 0.7769 - val_loss: 0.4306 - val_accuracy: 0.7727
Epoch 24/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4511 - accuracy: 0.7785 - val_loss: 0.4308 - val_accuracy: 0.7727
Epoch 25/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4500 - accuracy: 0.7752 - val_loss: 0.4292 - val_accuracy: 0.7727
Epoch 26/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4488 - accuracy: 0.7769 - val_loss: 0.4289 - val_accuracy: 0.7727
Epoch 27/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4481 - accuracy: 0.7818 - val_loss: 0.4293 - val_accuracy: 0.7727
Epoch 28/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4475 - accuracy: 0.7769 - val_loss: 0.4280 - val_accuracy: 0.7727
Epoch 29/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4465 - accuracy: 0.7801 - val_loss: 0.4285 - val_accuracy: 0.7727
Epoch 30/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4461 - accuracy: 0.7834 - val_loss: 0.4297 - val_accuracy: 0.7792
Epoch 31/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4451 - accuracy: 0.7769 - val_loss: 0.4306 - val_accuracy: 0.7792
Epoch 32/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4439 - accuracy: 0.7801 - val_loss: 0.4294 - val_accuracy: 0.7792
Epoch 33/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4434 - accuracy: 0.7834 - val_loss: 0.4267 - val_accuracy: 0.7662
Epoch 34/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4423 - accuracy: 0.7866 - val_loss: 0.4268 - val_accuracy: 0.7792
Epoch 35/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4419 - accuracy: 0.7964 - val_loss: 0.4255 - val_accuracy: 0.7727
Epoch 36/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4409 - accuracy: 0.7883 - val_loss: 0.4257 - val_accuracy: 0.7727
Epoch 37/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4402 - accuracy: 0.7964 - val_loss: 0.4256 - val_accuracy: 0.7792
Epoch 38/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4399 - accuracy: 0.7932 - val_loss: 0.4255 - val_accuracy: 0.7792
Epoch 39/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4389 - accuracy: 0.7964 - val_loss: 0.4249 - val_accuracy: 0.7727
Epoch 40/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4383 - accuracy: 0.7932 - val_loss: 0.4229 - val_accuracy: 0.7727
Epoch 41/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4379 - accuracy: 0.7899 - val_loss: 0.4234 - val_accuracy: 0.7727
Epoch 42/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4367 - accuracy: 0.7980 - val_loss: 0.4224 - val_accuracy: 0.7727
Epoch 43/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4360 - accuracy: 0.8013 - val_loss: 0.4203 - val_accuracy: 0.7727
Epoch 44/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4355 - accuracy: 0.7964 - val_loss: 0.4207 - val_accuracy: 0.7727
Epoch 45/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4349 - accuracy: 0.7932 - val_loss: 0.4213 - val_accuracy: 0.7727
Epoch 46/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4343 - accuracy: 0.7964 - val_loss: 0.4211 - val_accuracy: 0.7727
Epoch 47/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4336 - accuracy: 0.7948 - val_loss: 0.4195 - val_accuracy: 0.7727
Epoch 48/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4330 - accuracy: 0.7948 - val_loss: 0.4213 - val_accuracy: 0.7727
Epoch 49/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4325 - accuracy: 0.7948 - val_loss: 0.4209 - val_accuracy: 0.7727
Epoch 50/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4320 - accuracy: 0.7964 - val_loss: 0.4227 - val_accuracy: 0.7727
Epoch 51/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4314 - accuracy: 0.7948 - val_loss: 0.4228 - val_accuracy: 0.7727
Epoch 52/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4308 - accuracy: 0.7980 - val_loss: 0.4243 - val_accuracy: 0.7727
Epoch 53/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4302 - accuracy: 0.7948 - val_loss: 0.4252 - val_accuracy: 0.7792
Epoch 54/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4302 - accuracy: 0.7964 - val_loss: 0.4243 - val_accuracy: 0.7727
Epoch 55/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4293 - accuracy: 0.7948 - val_loss: 0.4233 - val_accuracy: 0.7727
Epoch 56/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4288 - accuracy: 0.7948 - val_loss: 0.4227 - val_accuracy: 0.7727
Epoch 57/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4284 - accuracy: 0.7980 - val_loss: 0.4218 - val_accuracy: 0.7727
Epoch 58/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4283 - accuracy: 0.7964 - val_loss: 0.4226 - val_accuracy: 0.7792
Epoch 59/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4276 - accuracy: 0.7964 - val_loss: 0.4213 - val_accuracy: 0.7727
Epoch 60/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4271 - accuracy: 0.7980 - val_loss: 0.4216 - val_accuracy: 0.7727
Epoch 61/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4266 - accuracy: 0.7964 - val_loss: 0.4226 - val_accuracy: 0.7792
Epoch 62/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4261 - accuracy: 0.7964 - val_loss: 0.4238 - val_accuracy: 0.7792
Epoch 63/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4257 - accuracy: 0.7964 - val_loss: 0.4215 - val_accuracy: 0.7792
Epoch 64/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4250 - accuracy: 0.8013 - val_loss: 0.4214 - val_accuracy: 0.7792
Epoch 65/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4251 - accuracy: 0.7980 - val_loss: 0.4196 - val_accuracy: 0.7792
Epoch 66/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4244 - accuracy: 0.7997 - val_loss: 0.4193 - val_accuracy: 0.7792
Epoch 67/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4241 - accuracy: 0.7964 - val_loss: 0.4195 - val_accuracy: 0.7727
Epoch 68/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4234 - accuracy: 0.7948 - val_loss: 0.4187 - val_accuracy: 0.7727
Epoch 69/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4233 - accuracy: 0.8013 - val_loss: 0.4193 - val_accuracy: 0.7727
Epoch 70/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4225 - accuracy: 0.7980 - val_loss: 0.4206 - val_accuracy: 0.7792
Epoch 71/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4224 - accuracy: 0.8013 - val_loss: 0.4205 - val_accuracy: 0.7792
Epoch 72/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4219 - accuracy: 0.7997 - val_loss: 0.4211 - val_accuracy: 0.7792
Epoch 73/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4220 - accuracy: 0.8013 - val_loss: 0.4205 - val_accuracy: 0.7792
Epoch 74/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4210 - accuracy: 0.8029 - val_loss: 0.4205 - val_accuracy: 0.7792
Epoch 75/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4209 - accuracy: 0.7980 - val_loss: 0.4227 - val_accuracy: 0.7792
Epoch 76/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4202 - accuracy: 0.7997 - val_loss: 0.4223 - val_accuracy: 0.7727
Epoch 77/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4200 - accuracy: 0.8046 - val_loss: 0.4211 - val_accuracy: 0.7792
Epoch 78/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4195 - accuracy: 0.8029 - val_loss: 0.4209 - val_accuracy: 0.7792
Epoch 79/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4193 - accuracy: 0.8046 - val_loss: 0.4210 - val_accuracy: 0.7792
Epoch 80/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4189 - accuracy: 0.8062 - val_loss: 0.4206 - val_accuracy: 0.7792
Epoch 81/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4186 - accuracy: 0.8013 - val_loss: 0.4193 - val_accuracy: 0.7792
Epoch 82/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4183 - accuracy: 0.8062 - val_loss: 0.4202 - val_accuracy: 0.7792
Epoch 83/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4183 - accuracy: 0.8062 - val_loss: 0.4207 - val_accuracy: 0.7727
Epoch 84/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4176 - accuracy: 0.8029 - val_loss: 0.4211 - val_accuracy: 0.7727
Epoch 85/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4173 - accuracy: 0.8029 - val_loss: 0.4221 - val_accuracy: 0.7792
Epoch 86/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4172 - accuracy: 0.8013 - val_loss: 0.4223 - val_accuracy: 0.7792
Epoch 87/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4166 - accuracy: 0.8029 - val_loss: 0.4212 - val_accuracy: 0.7727
Epoch 88/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4162 - accuracy: 0.8029 - val_loss: 0.4207 - val_accuracy: 0.7792
Epoch 89/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4160 - accuracy: 0.8046 - val_loss: 0.4211 - val_accuracy: 0.7792
Epoch 90/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4160 - accuracy: 0.8046 - val_loss: 0.4200 - val_accuracy: 0.7792
Epoch 91/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4159 - accuracy: 0.8046 - val_loss: 0.4203 - val_accuracy: 0.7792
Epoch 92/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4154 - accuracy: 0.8029 - val_loss: 0.4196 - val_accuracy: 0.7857
Epoch 93/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4152 - accuracy: 0.8029 - val_loss: 0.4198 - val_accuracy: 0.7792
Epoch 94/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4144 - accuracy: 0.8029 - val_loss: 0.4206 - val_accuracy: 0.7727
Epoch 95/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4144 - accuracy: 0.8078 - val_loss: 0.4199 - val_accuracy: 0.7857
Epoch 96/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4138 - accuracy: 0.8046 - val_loss: 0.4191 - val_accuracy: 0.7857
Epoch 97/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4138 - accuracy: 0.8013 - val_loss: 0.4207 - val_accuracy: 0.7792
Epoch 98/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4128 - accuracy: 0.7997 - val_loss: 0.4232 - val_accuracy: 0.7792
Epoch 99/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4135 - accuracy: 0.8013 - val_loss: 0.4206 - val_accuracy: 0.7727
Epoch 100/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4131 - accuracy: 0.8013 - val_loss: 0.4197 - val_accuracy: 0.7727

# right numbers of neurons in the given layers- keras tuner hyperparameter

In [ ]:
def build_model(hp):
  model=Sequential()
  units=hp.Int('units',8,128, step=8)
  # 8-lower limit, 128-upper limit, step- iteration(every 8 points)
  model.add(Dense(units=units, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [ ]:
tuner=kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5,
                      directory='mydir', project_name='vikrant')

In [ ]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 09s

In [ ]:
tuner.get_best_hyperparameters()

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'units': 64}

In [ ]:
model=tuner.get_best_models(num_models=1)[0]

In [ ]:
model.fit(X_train,y_train, epochs=100, initial_epoch=6, batch_size=32,
          validation_data=(X_test, y_test))

Epoch 7/100
20/20 [==============================] - 1s 12ms/step - loss: 0.4837 - accuracy: 0.7655 - val_loss: 0.4541 - val_accuracy: 0.7987
Epoch 8/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4750 - accuracy: 0.7736 - val_loss: 0.4468 - val_accuracy: 0.7922
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4692 - accuracy: 0.7769 - val_loss: 0.4415 - val_accuracy: 0.7922
Epoch 10/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4653 - accuracy: 0.7769 - val_loss: 0.4383 - val_accuracy: 0.7857
Epoch 11/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4622 - accuracy: 0.7769 - val_loss: 0.4364 - val_accuracy: 0.7857
Epoch 12/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4593 - accuracy: 0.7785 - val_loss: 0.4326 - val_accuracy: 0.7792
Epoch 13/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4566 - accuracy: 0.7801 - val_loss: 0.4307 - val_accuracy: 0.7727
Epoch 14/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4546 - accuracy: 0.7801 - val_loss: 0.4306 - val_accuracy: 0.7792
Epoch 15/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4529 - accuracy: 0.7818 - val_loss: 0.4303 - val_accuracy: 0.7792
Epoch 16/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4513 - accuracy: 0.7866 - val_loss: 0.4292 - val_accuracy: 0.7792
Epoch 17/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4498 - accuracy: 0.7834 - val_loss: 0.4286 - val_accuracy: 0.7792
Epoch 18/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4484 - accuracy: 0.7785 - val_loss: 0.4300 - val_accuracy: 0.7792
Epoch 19/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4472 - accuracy: 0.7834 - val_loss: 0.4273 - val_accuracy: 0.7922
Epoch 20/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4459 - accuracy: 0.7834 - val_loss: 0.4261 - val_accuracy: 0.7792
Epoch 21/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4445 - accuracy: 0.7850 - val_loss: 0.4249 - val_accuracy: 0.7727
Epoch 22/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4436 - accuracy: 0.7866 - val_loss: 0.4255 - val_accuracy: 0.7792
Epoch 23/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4429 - accuracy: 0.7850 - val_loss: 0.4237 - val_accuracy: 0.7792
Epoch 24/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4409 - accuracy: 0.7883 - val_loss: 0.4225 - val_accuracy: 0.7857
Epoch 25/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4405 - accuracy: 0.7834 - val_loss: 0.4236 - val_accuracy: 0.7857
Epoch 26/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4393 - accuracy: 0.7883 - val_loss: 0.4253 - val_accuracy: 0.7922
Epoch 27/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4384 - accuracy: 0.7915 - val_loss: 0.4244 - val_accuracy: 0.7922
Epoch 28/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4374 - accuracy: 0.7915 - val_loss: 0.4246 - val_accuracy: 0.7857
Epoch 29/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4370 - accuracy: 0.7915 - val_loss: 0.4227 - val_accuracy: 0.7857
Epoch 30/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4364 - accuracy: 0.7883 - val_loss: 0.4239 - val_accuracy: 0.7857
Epoch 31/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4349 - accuracy: 0.7899 - val_loss: 0.4225 - val_accuracy: 0.7727
Epoch 32/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4347 - accuracy: 0.7932 - val_loss: 0.4242 - val_accuracy: 0.7662
Epoch 33/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4341 - accuracy: 0.7948 - val_loss: 0.4235 - val_accuracy: 0.7792
Epoch 34/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4328 - accuracy: 0.7932 - val_loss: 0.4232 - val_accuracy: 0.7922
Epoch 35/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4324 - accuracy: 0.7883 - val_loss: 0.4208 - val_accuracy: 0.7857
Epoch 36/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4318 - accuracy: 0.7948 - val_loss: 0.4212 - val_accuracy: 0.7792
Epoch 37/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4312 - accuracy: 0.7915 - val_loss: 0.4207 - val_accuracy: 0.7857
Epoch 38/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4306 - accuracy: 0.7932 - val_loss: 0.4213 - val_accuracy: 0.7727
Epoch 39/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4296 - accuracy: 0.7964 - val_loss: 0.4227 - val_accuracy: 0.7662
Epoch 40/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4299 - accuracy: 0.7964 - val_loss: 0.4235 - val_accuracy: 0.7662
Epoch 41/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4284 - accuracy: 0.7948 - val_loss: 0.4223 - val_accuracy: 0.7662
Epoch 42/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4279 - accuracy: 0.7997 - val_loss: 0.4215 - val_accuracy: 0.7792
Epoch 43/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4274 - accuracy: 0.8013 - val_loss: 0.4201 - val_accuracy: 0.7792
Epoch 44/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4269 - accuracy: 0.8029 - val_loss: 0.4192 - val_accuracy: 0.7857
Epoch 45/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4261 - accuracy: 0.7964 - val_loss: 0.4180 - val_accuracy: 0.7662
Epoch 46/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4255 - accuracy: 0.8013 - val_loss: 0.4190 - val_accuracy: 0.7727
Epoch 47/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4249 - accuracy: 0.7964 - val_loss: 0.4211 - val_accuracy: 0.7792
Epoch 48/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4243 - accuracy: 0.7997 - val_loss: 0.4223 - val_accuracy: 0.7792
Epoch 49/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4235 - accuracy: 0.8046 - val_loss: 0.4213 - val_accuracy: 0.7922
Epoch 50/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4230 - accuracy: 0.7997 - val_loss: 0.4206 - val_accuracy: 0.7857
Epoch 51/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4225 - accuracy: 0.8029 - val_loss: 0.4201 - val_accuracy: 0.7857
Epoch 52/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4220 - accuracy: 0.7997 - val_loss: 0.4189 - val_accuracy: 0.7857
Epoch 53/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4216 - accuracy: 0.8013 - val_loss: 0.4203 - val_accuracy: 0.7792
Epoch 54/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4210 - accuracy: 0.8013 - val_loss: 0.4197 - val_accuracy: 0.7857
Epoch 55/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4207 - accuracy: 0.8062 - val_loss: 0.4197 - val_accuracy: 0.7857
Epoch 56/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4199 - accuracy: 0.8046 - val_loss: 0.4213 - val_accuracy: 0.7662
Epoch 57/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4194 - accuracy: 0.8029 - val_loss: 0.4195 - val_accuracy: 0.7727
Epoch 58/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4186 - accuracy: 0.8046 - val_loss: 0.4193 - val_accuracy: 0.7792
Epoch 59/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4182 - accuracy: 0.8046 - val_loss: 0.4200 - val_accuracy: 0.7792
Epoch 60/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4178 - accuracy: 0.8029 - val_loss: 0.4203 - val_accuracy: 0.7792
Epoch 61/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4176 - accuracy: 0.8078 - val_loss: 0.4199 - val_accuracy: 0.7857
Epoch 62/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4167 - accuracy: 0.8046 - val_loss: 0.4200 - val_accuracy: 0.7857
Epoch 63/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4165 - accuracy: 0.8029 - val_loss: 0.4212 - val_accuracy: 0.7792
Epoch 64/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4158 - accuracy: 0.8013 - val_loss: 0.4197 - val_accuracy: 0.7792
Epoch 65/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4155 - accuracy: 0.8062 - val_loss: 0.4202 - val_accuracy: 0.7792
Epoch 66/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4146 - accuracy: 0.7980 - val_loss: 0.4197 - val_accuracy: 0.7857
Epoch 67/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4142 - accuracy: 0.7964 - val_loss: 0.4195 - val_accuracy: 0.7792
Epoch 68/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4143 - accuracy: 0.8062 - val_loss: 0.4201 - val_accuracy: 0.7857
Epoch 69/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4133 - accuracy: 0.8078 - val_loss: 0.4202 - val_accuracy: 0.7792
Epoch 70/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4127 - accuracy: 0.8062 - val_loss: 0.4212 - val_accuracy: 0.7792
Epoch 71/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4123 - accuracy: 0.8111 - val_loss: 0.4222 - val_accuracy: 0.7792
Epoch 72/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4124 - accuracy: 0.8078 - val_loss: 0.4219 - val_accuracy: 0.7857
Epoch 73/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4114 - accuracy: 0.8111 - val_loss: 0.4231 - val_accuracy: 0.7857
Epoch 74/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4117 - accuracy: 0.8029 - val_loss: 0.4201 - val_accuracy: 0.7792
Epoch 75/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4107 - accuracy: 0.8094 - val_loss: 0.4198 - val_accuracy: 0.7857
Epoch 76/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4105 - accuracy: 0.8062 - val_loss: 0.4193 - val_accuracy: 0.7792
Epoch 77/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4100 - accuracy: 0.8078 - val_loss: 0.4191 - val_accuracy: 0.7792
Epoch 78/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4094 - accuracy: 0.8094 - val_loss: 0.4169 - val_accuracy: 0.7857
Epoch 79/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4091 - accuracy: 0.8143 - val_loss: 0.4191 - val_accuracy: 0.7857
Epoch 80/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4085 - accuracy: 0.8046 - val_loss: 0.4202 - val_accuracy: 0.7792
Epoch 81/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4084 - accuracy: 0.8062 - val_loss: 0.4188 - val_accuracy: 0.7792
Epoch 82/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4081 - accuracy: 0.8013 - val_loss: 0.4181 - val_accuracy: 0.7857
Epoch 83/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4074 - accuracy: 0.8029 - val_loss: 0.4171 - val_accuracy: 0.7857
Epoch 84/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4072 - accuracy: 0.8111 - val_loss: 0.4191 - val_accuracy: 0.7857
Epoch 85/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4072 - accuracy: 0.8094 - val_loss: 0.4205 - val_accuracy: 0.7792
Epoch 86/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4066 - accuracy: 0.8094 - val_loss: 0.4194 - val_accuracy: 0.7792
Epoch 87/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4058 - accuracy: 0.8127 - val_loss: 0.4162 - val_accuracy: 0.7727
Epoch 88/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4049 - accuracy: 0.8094 - val_loss: 0.4177 - val_accuracy: 0.7857
Epoch 89/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4046 - accuracy: 0.8094 - val_loss: 0.4200 - val_accuracy: 0.7792
Epoch 90/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4043 - accuracy: 0.8111 - val_loss: 0.4164 - val_accuracy: 0.7857
Epoch 91/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4045 - accuracy: 0.8127 - val_loss: 0.4177 - val_accuracy: 0.7792
Epoch 92/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4045 - accuracy: 0.8046 - val_loss: 0.4185 - val_accuracy: 0.7857
Epoch 93/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4036 - accuracy: 0.8111 - val_loss: 0.4177 - val_accuracy: 0.7857
Epoch 94/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4034 - accuracy: 0.8111 - val_loss: 0.4191 - val_accuracy: 0.7857
Epoch 95/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4025 - accuracy: 0.8094 - val_loss: 0.4186 - val_accuracy: 0.7857
Epoch 96/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4022 - accuracy: 0.8111 - val_loss: 0.4216 - val_accuracy: 0.7792
Epoch 97/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4024 - accuracy: 0.8111 - val_loss: 0.4194 - val_accuracy: 0.7857
Epoch 98/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4012 - accuracy: 0.8143 - val_loss: 0.4173 - val_accuracy: 0.7857
Epoch 99/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4013 - accuracy: 0.8111 - val_loss: 0.4184 - val_accuracy: 0.7857
Epoch 100/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4008 - accuracy: 0.8078 - val_loss: 0.4182 - val_accuracy: 0.7857

# No of hidden layers

In [ ]:
def build_model(hp):
  model=Sequential()
  model.add(Dense(64,activation='relu', input_dim=8))
  for i in range(hp.Int('num_hidden_layers', min_value=1, max_value=20)):
    model.add(Dense(64, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [ ]:
tuner=kt.RandomSearch(build_model, objective='val_accuracy',
                      max_trials=5, directory='mydir', project_name='vikrant2')

In [ ]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 05s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 21s

In [ ]:
tuner.get_best_hyperparameters()

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_hidden_layers': 1}

In [ ]:
model=tuner.get_best_models(num_models=1)[0]

In [ ]:
model.fit(X_train,y_train, epochs=100, initial_epoch=6, batch_size=32,
          validation_data=(X_test, y_test))

Epoch 7/100
20/20 [==============================] - 2s 27ms/step - loss: 0.4440 - accuracy: 0.7850 - val_loss: 0.4325 - val_accuracy: 0.7857
Epoch 8/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4412 - accuracy: 0.7866 - val_loss: 0.4226 - val_accuracy: 0.7792
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4356 - accuracy: 0.7915 - val_loss: 0.4373 - val_accuracy: 0.7727
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4326 - accuracy: 0.7980 - val_loss: 0.4278 - val_accuracy: 0.7857
Epoch 11/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4313 - accuracy: 0.7899 - val_loss: 0.4359 - val_accuracy: 0.7792
Epoch 12/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4276 - accuracy: 0.7980 - val_loss: 0.4252 - val_accuracy: 0.7987
Epoch 13/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4255 - accuracy: 0.7964 - val_loss: 0.4254 - val_accuracy: 0.7987
Epoch 14/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4231 - accuracy: 0.8013 - val_loss: 0.4226 - val_accuracy: 0.7792
Epoch 15/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4194 - accuracy: 0.7997 - val_loss: 0.4296 - val_accuracy: 0.7727
Epoch 16/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4165 - accuracy: 0.8013 - val_loss: 0.4324 - val_accuracy: 0.7727
Epoch 17/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4157 - accuracy: 0.8046 - val_loss: 0.4352 - val_accuracy: 0.7792
Epoch 18/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4121 - accuracy: 0.7980 - val_loss: 0.4370 - val_accuracy: 0.7792
Epoch 19/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4117 - accuracy: 0.8013 - val_loss: 0.4353 - val_accuracy: 0.7727
Epoch 20/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4088 - accuracy: 0.8062 - val_loss: 0.4318 - val_accuracy: 0.7857
Epoch 21/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4055 - accuracy: 0.8192 - val_loss: 0.4219 - val_accuracy: 0.7857
Epoch 22/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4042 - accuracy: 0.8062 - val_loss: 0.4391 - val_accuracy: 0.7922
Epoch 23/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4020 - accuracy: 0.8111 - val_loss: 0.4300 - val_accuracy: 0.7727
Epoch 24/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4000 - accuracy: 0.8143 - val_loss: 0.4241 - val_accuracy: 0.7922
Epoch 25/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3971 - accuracy: 0.8062 - val_loss: 0.4468 - val_accuracy: 0.7857
Epoch 26/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3959 - accuracy: 0.8046 - val_loss: 0.4272 - val_accuracy: 0.7857
Epoch 27/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3929 - accuracy: 0.8208 - val_loss: 0.4246 - val_accuracy: 0.7857
Epoch 28/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3913 - accuracy: 0.8143 - val_loss: 0.4342 - val_accuracy: 0.7792
Epoch 29/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3892 - accuracy: 0.8241 - val_loss: 0.4236 - val_accuracy: 0.7857
Epoch 30/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3877 - accuracy: 0.8143 - val_loss: 0.4463 - val_accuracy: 0.7792
Epoch 31/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3855 - accuracy: 0.8176 - val_loss: 0.4474 - val_accuracy: 0.7727
Epoch 32/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3841 - accuracy: 0.8208 - val_loss: 0.4520 - val_accuracy: 0.7857
Epoch 33/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3792 - accuracy: 0.8208 - val_loss: 0.4311 - val_accuracy: 0.7922
Epoch 34/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3801 - accuracy: 0.8257 - val_loss: 0.4356 - val_accuracy: 0.7857
Epoch 35/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3765 - accuracy: 0.8192 - val_loss: 0.4285 - val_accuracy: 0.7857
Epoch 36/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3761 - accuracy: 0.8160 - val_loss: 0.4303 - val_accuracy: 0.7922
Epoch 37/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3716 - accuracy: 0.8241 - val_loss: 0.4355 - val_accuracy: 0.7857
Epoch 38/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3709 - accuracy: 0.8290 - val_loss: 0.4397 - val_accuracy: 0.7727
Epoch 39/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3699 - accuracy: 0.8290 - val_loss: 0.4387 - val_accuracy: 0.7792
Epoch 40/100
20/20 [==============================] - 0s 6ms/step - loss: 0.3658 - accuracy: 0.8274 - val_loss: 0.4324 - val_accuracy: 0.7857
Epoch 41/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3632 - accuracy: 0.8355 - val_loss: 0.4390 - val_accuracy: 0.7857
Epoch 42/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3599 - accuracy: 0.8420 - val_loss: 0.4375 - val_accuracy: 0.7857
Epoch 43/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3610 - accuracy: 0.8290 - val_loss: 0.4419 - val_accuracy: 0.7857
Epoch 44/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3576 - accuracy: 0.8290 - val_loss: 0.4398 - val_accuracy: 0.7857
Epoch 45/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3571 - accuracy: 0.8322 - val_loss: 0.4348 - val_accuracy: 0.7727
Epoch 46/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3550 - accuracy: 0.8355 - val_loss: 0.4552 - val_accuracy: 0.7857
Epoch 47/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3551 - accuracy: 0.8388 - val_loss: 0.4396 - val_accuracy: 0.8052
Epoch 48/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3522 - accuracy: 0.8404 - val_loss: 0.4424 - val_accuracy: 0.7857
Epoch 49/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3492 - accuracy: 0.8469 - val_loss: 0.4605 - val_accuracy: 0.7857
Epoch 50/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3477 - accuracy: 0.8485 - val_loss: 0.4585 - val_accuracy: 0.7792
Epoch 51/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3450 - accuracy: 0.8502 - val_loss: 0.4349 - val_accuracy: 0.7662
Epoch 52/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3437 - accuracy: 0.8453 - val_loss: 0.4496 - val_accuracy: 0.7922
Epoch 53/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3410 - accuracy: 0.8502 - val_loss: 0.4385 - val_accuracy: 0.7987
Epoch 54/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3389 - accuracy: 0.8485 - val_loss: 0.4405 - val_accuracy: 0.7792
Epoch 55/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3366 - accuracy: 0.8518 - val_loss: 0.4398 - val_accuracy: 0.7922
Epoch 56/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3358 - accuracy: 0.8518 - val_loss: 0.4307 - val_accuracy: 0.7987
Epoch 57/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3354 - accuracy: 0.8502 - val_loss: 0.4427 - val_accuracy: 0.7987
Epoch 58/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3327 - accuracy: 0.8469 - val_loss: 0.4447 - val_accuracy: 0.7987
Epoch 59/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3305 - accuracy: 0.8518 - val_loss: 0.4403 - val_accuracy: 0.8052
Epoch 60/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3286 - accuracy: 0.8534 - val_loss: 0.4408 - val_accuracy: 0.8052
Epoch 61/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3255 - accuracy: 0.8632 - val_loss: 0.4391 - val_accuracy: 0.7857
Epoch 62/100
20/20 [==============================] - 0s 6ms/step - loss: 0.3237 - accuracy: 0.8681 - val_loss: 0.4393 - val_accuracy: 0.7987
Epoch 63/100
20/20 [==============================] - 0s 6ms/step - loss: 0.3229 - accuracy: 0.8534 - val_loss: 0.4565 - val_accuracy: 0.8052
Epoch 64/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3229 - accuracy: 0.8632 - val_loss: 0.4491 - val_accuracy: 0.8052
Epoch 65/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3203 - accuracy: 0.8567 - val_loss: 0.4523 - val_accuracy: 0.7987
Epoch 66/100
20/20 [==============================] - 0s 6ms/step - loss: 0.3185 - accuracy: 0.8567 - val_loss: 0.4572 - val_accuracy: 0.7792
Epoch 67/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3148 - accuracy: 0.8648 - val_loss: 0.4604 - val_accuracy: 0.7922
Epoch 68/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3144 - accuracy: 0.8664 - val_loss: 0.4432 - val_accuracy: 0.8052
Epoch 69/100
20/20 [==============================] - 0s 8ms/step - loss: 0.3138 - accuracy: 0.8632 - val_loss: 0.4455 - val_accuracy: 0.7987
Epoch 70/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3087 - accuracy: 0.8697 - val_loss: 0.4565 - val_accuracy: 0.8052
Epoch 71/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3113 - accuracy: 0.8730 - val_loss: 0.4440 - val_accuracy: 0.8052
Epoch 72/100
20/20 [==============================] - 0s 6ms/step - loss: 0.3067 - accuracy: 0.8616 - val_loss: 0.4443 - val_accuracy: 0.7987
Epoch 73/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3058 - accuracy: 0.8779 - val_loss: 0.4470 - val_accuracy: 0.7922
Epoch 74/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3034 - accuracy: 0.8697 - val_loss: 0.4790 - val_accuracy: 0.7662
Epoch 75/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3005 - accuracy: 0.8811 - val_loss: 0.4487 - val_accuracy: 0.7792
Epoch 76/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2980 - accuracy: 0.8730 - val_loss: 0.4404 - val_accuracy: 0.7857
Epoch 77/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2971 - accuracy: 0.8730 - val_loss: 0.4826 - val_accuracy: 0.7792
Epoch 78/100
20/20 [==============================] - 0s 6ms/step - loss: 0.2952 - accuracy: 0.8827 - val_loss: 0.4647 - val_accuracy: 0.7792
Epoch 79/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2932 - accuracy: 0.8746 - val_loss: 0.4594 - val_accuracy: 0.7792
Epoch 80/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2930 - accuracy: 0.8779 - val_loss: 0.4878 - val_accuracy: 0.7792
Epoch 81/100
20/20 [==============================] - 0s 6ms/step - loss: 0.2897 - accuracy: 0.8811 - val_loss: 0.4756 - val_accuracy: 0.7922
Epoch 82/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2889 - accuracy: 0.8681 - val_loss: 0.4552 - val_accuracy: 0.7987
Epoch 83/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2858 - accuracy: 0.8795 - val_loss: 0.4901 - val_accuracy: 0.7727
Epoch 84/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2849 - accuracy: 0.8779 - val_loss: 0.4508 - val_accuracy: 0.7857
Epoch 85/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2821 - accuracy: 0.8779 - val_loss: 0.4679 - val_accuracy: 0.7922
Epoch 86/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2814 - accuracy: 0.8827 - val_loss: 0.5328 - val_accuracy: 0.7597
Epoch 87/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2801 - accuracy: 0.8860 - val_loss: 0.4436 - val_accuracy: 0.7857
Epoch 88/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2782 - accuracy: 0.8860 - val_loss: 0.4647 - val_accuracy: 0.7792
Epoch 89/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2752 - accuracy: 0.8811 - val_loss: 0.4863 - val_accuracy: 0.7727
Epoch 90/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2730 - accuracy: 0.8844 - val_loss: 0.4557 - val_accuracy: 0.7922
Epoch 91/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2718 - accuracy: 0.8909 - val_loss: 0.4705 - val_accuracy: 0.7922
Epoch 92/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2708 - accuracy: 0.8876 - val_loss: 0.4687 - val_accuracy: 0.7922
Epoch 93/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2687 - accuracy: 0.8876 - val_loss: 0.4757 - val_accuracy: 0.7857
Epoch 94/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2650 - accuracy: 0.8925 - val_loss: 0.4717 - val_accuracy: 0.7792
Epoch 95/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2642 - accuracy: 0.8909 - val_loss: 0.4642 - val_accuracy: 0.7857
Epoch 96/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2594 - accuracy: 0.8941 - val_loss: 0.4470 - val_accuracy: 0.7792
Epoch 97/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2625 - accuracy: 0.8860 - val_loss: 0.4765 - val_accuracy: 0.7857
Epoch 98/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2554 - accuracy: 0.9039 - val_loss: 0.4816 - val_accuracy: 0.7987
Epoch 99/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2595 - accuracy: 0.8941 - val_loss: 0.4715 - val_accuracy: 0.7922
Epoch 100/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2568 - accuracy: 0.8909 - val_loss: 0.4923 - val_accuracy: 0.7727

# Keras_tuner Hyperparameter tuning all at once

In [ ]:
def build_model(hp):
  model=Sequential()
  counter=0

  for i in range(hp.Int('num_of_layers', min_value=1, max_value=20)):
    if counter == 0:
      model.add(Dense(hp.Int('units'+str(i), min_value=8, max_value=256),
                      activation= hp.Choice('activation'+str(i),
                                            values=['relu', 'leaky_relu', 'tanh','softmax',
                                                    'sigmoid','linear','elu']),
                      input_dim=8))
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1,0.2,0.3,0.35,0.4,0.45,0.5])))
    else:
      model.add(Dense(hp.Int('units'+str(i), min_value=8, max_value=256),
                      activation= hp.Choice('activation'+str(i),
                                            values=['relu', 'leaky_relu', 'tanh','softmax',
                                                    'sigmoid','linear','elu'])))
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1,0.2,0.3,0.35,0.4,0.45,0.5])))
    counter+=1
  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['rmsprop','adam','adagrad',
                                                        'adadelta','sgd','nadam']),
                                    loss='binary_crossentropy', metrics=['accuracy'] )
  return model

In [ ]:
tuner= kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5,
                       directory='mydir', project_name='ALL1')

In [ ]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 07s]
val_accuracy: 0.6688311696052551

Best val_accuracy So Far: 0.6688311696052551
Total elapsed time: 00h 00m 26s

In [ ]:
tuner.get_best_hyperparameters()

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_of_layers': 11,
 'units0': 37,
 'activation0': 'leaky_relu',
 'dropout0': 0.4,
 'optimizer': 'sgd',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'dropout3': 0.1,
 'units4': 8,
 'activation4': 'relu',
 'dropout4': 0.1,
 'units5': 8,
 'activation5': 'relu',
 'dropout5': 0.1,
 'units6': 8,
 'activation6': 'relu',
 'dropout6': 0.1,
 'units7': 8,
 'activation7': 'relu',
 'dropout7': 0.1,
 'units8': 8,
 'activation8': 'relu',
 'dropout8': 0.1,
 'units9': 8,
 'activation9': 'relu',
 'dropout9': 0.1,
 'units10': 8,
 'activation10': 'relu',
 'dropout10': 0.1}

In [ ]:
model= tuner.get_best_models(num_models=1)[0]

In [ ]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6,
          validation_data=(X_test, y_test))

Epoch 7/100
20/20 [==============================] - 2s 19ms/step - loss: 0.6773 - accuracy: 0.6466 - val_loss: 0.6684 - val_accuracy: 0.6688
Epoch 8/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6710 - accuracy: 0.6466 - val_loss: 0.6608 - val_accuracy: 0.6688
Epoch 9/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6605 - accuracy: 0.6466 - val_loss: 0.6543 - val_accuracy: 0.6688
Epoch 10/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6654 - accuracy: 0.6466 - val_loss: 0.6496 - val_accuracy: 0.6688
Epoch 11/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6633 - accuracy: 0.6466 - val_loss: 0.6460 - val_accuracy: 0.6688
Epoch 12/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6577 - accuracy: 0.6466 - val_loss: 0.6431 - val_accuracy: 0.6688
Epoch 13/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6571 - accuracy: 0.6466 - val_loss: 0.6399 - val_accuracy: 0.6688
Epoch 14/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6528 - accuracy: 0.6466 - val_loss: 0.6374 - val_accuracy: 0.6688
Epoch 15/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6540 - accuracy: 0.6466 - val_loss: 0.6356 - val_accuracy: 0.6688
Epoch 16/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6421 - accuracy: 0.6466 - val_loss: 0.6335 - val_accuracy: 0.6688
Epoch 17/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6502 - accuracy: 0.6466 - val_loss: 0.6327 - val_accuracy: 0.6688
Epoch 18/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6467 - accuracy: 0.6466 - val_loss: 0.6320 - val_accuracy: 0.6688
Epoch 19/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6485 - accuracy: 0.6466 - val_loss: 0.6307 - val_accuracy: 0.6688
Epoch 20/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6481 - accuracy: 0.6466 - val_loss: 0.6300 - val_accuracy: 0.6688
Epoch 21/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6516 - accuracy: 0.6466 - val_loss: 0.6292 - val_accuracy: 0.6688
Epoch 22/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6497 - accuracy: 0.6466 - val_loss: 0.6286 - val_accuracy: 0.6688
Epoch 23/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6448 - accuracy: 0.6466 - val_loss: 0.6281 - val_accuracy: 0.6688
Epoch 24/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6451 - accuracy: 0.6466 - val_loss: 0.6269 - val_accuracy: 0.6688
Epoch 25/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6438 - accuracy: 0.6466 - val_loss: 0.6259 - val_accuracy: 0.6688
Epoch 26/100
20/20 [==============================] - 0s 10ms/step - loss: 0.6456 - accuracy: 0.6466 - val_loss: 0.6257 - val_accuracy: 0.6688
Epoch 27/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6459 - accuracy: 0.6466 - val_loss: 0.6252 - val_accuracy: 0.6688
Epoch 28/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6500 - accuracy: 0.6466 - val_loss: 0.6247 - val_accuracy: 0.6688
Epoch 29/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6480 - accuracy: 0.6466 - val_loss: 0.6241 - val_accuracy: 0.6688
Epoch 30/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6409 - accuracy: 0.6466 - val_loss: 0.6235 - val_accuracy: 0.6688
Epoch 31/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6438 - accuracy: 0.6466 - val_loss: 0.6228 - val_accuracy: 0.6688
Epoch 32/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6368 - accuracy: 0.6466 - val_loss: 0.6220 - val_accuracy: 0.6688
Epoch 33/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6502 - accuracy: 0.6466 - val_loss: 0.6217 - val_accuracy: 0.6688
Epoch 34/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6454 - accuracy: 0.6466 - val_loss: 0.6211 - val_accuracy: 0.6688
Epoch 35/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6452 - accuracy: 0.6466 - val_loss: 0.6204 - val_accuracy: 0.6688
Epoch 36/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6462 - accuracy: 0.6466 - val_loss: 0.6196 - val_accuracy: 0.6688
Epoch 37/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6393 - accuracy: 0.6466 - val_loss: 0.6186 - val_accuracy: 0.6688
Epoch 38/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6379 - accuracy: 0.6466 - val_loss: 0.6177 - val_accuracy: 0.6688
Epoch 39/100
20/20 [==============================] - 0s 11ms/step - loss: 0.6448 - accuracy: 0.6466 - val_loss: 0.6171 - val_accuracy: 0.6688
Epoch 40/100
20/20 [==============================] - 0s 12ms/step - loss: 0.6412 - accuracy: 0.6466 - val_loss: 0.6164 - val_accuracy: 0.6688
Epoch 41/100
20/20 [==============================] - 0s 12ms/step - loss: 0.6413 - accuracy: 0.6466 - val_loss: 0.6158 - val_accuracy: 0.6688
Epoch 42/100
20/20 [==============================] - 0s 11ms/step - loss: 0.6393 - accuracy: 0.6466 - val_loss: 0.6147 - val_accuracy: 0.6688
Epoch 43/100
20/20 [==============================] - 0s 11ms/step - loss: 0.6370 - accuracy: 0.6466 - val_loss: 0.6135 - val_accuracy: 0.6688
Epoch 44/100
20/20 [==============================] - 0s 12ms/step - loss: 0.6420 - accuracy: 0.6466 - val_loss: 0.6124 - val_accuracy: 0.6688
Epoch 45/100
20/20 [==============================] - 0s 12ms/step - loss: 0.6433 - accuracy: 0.6466 - val_loss: 0.6116 - val_accuracy: 0.6688
Epoch 46/100
20/20 [==============================] - 0s 15ms/step - loss: 0.6362 - accuracy: 0.6466 - val_loss: 0.6103 - val_accuracy: 0.6688
Epoch 47/100
20/20 [==============================] - 0s 16ms/step - loss: 0.6402 - accuracy: 0.6466 - val_loss: 0.6089 - val_accuracy: 0.6688
Epoch 48/100
20/20 [==============================] - 0s 16ms/step - loss: 0.6335 - accuracy: 0.6466 - val_loss: 0.6074 - val_accuracy: 0.6688
Epoch 49/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6377 - accuracy: 0.6466 - val_loss: 0.6061 - val_accuracy: 0.6688
Epoch 50/100
20/20 [==============================] - 0s 13ms/step - loss: 0.6404 - accuracy: 0.6466 - val_loss: 0.6050 - val_accuracy: 0.6688
Epoch 51/100
20/20 [==============================] - 0s 18ms/step - loss: 0.6369 - accuracy: 0.6466 - val_loss: 0.6033 - val_accuracy: 0.6688
Epoch 52/100
20/20 [==============================] - 0s 10ms/step - loss: 0.6375 - accuracy: 0.6466 - val_loss: 0.6015 - val_accuracy: 0.6688
Epoch 53/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6323 - accuracy: 0.6466 - val_loss: 0.5988 - val_accuracy: 0.6688
Epoch 54/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6376 - accuracy: 0.6466 - val_loss: 0.5972 - val_accuracy: 0.6688
Epoch 55/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6291 - accuracy: 0.6466 - val_loss: 0.5951 - val_accuracy: 0.6688
Epoch 56/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6347 - accuracy: 0.6466 - val_loss: 0.5933 - val_accuracy: 0.6688
Epoch 57/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6288 - accuracy: 0.6466 - val_loss: 0.5917 - val_accuracy: 0.6688
Epoch 58/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6424 - accuracy: 0.6466 - val_loss: 0.5916 - val_accuracy: 0.6688
Epoch 59/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6262 - accuracy: 0.6466 - val_loss: 0.5892 - val_accuracy: 0.6688
Epoch 60/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6262 - accuracy: 0.6466 - val_loss: 0.5872 - val_accuracy: 0.6688
Epoch 61/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6358 - accuracy: 0.6466 - val_loss: 0.5868 - val_accuracy: 0.6688
Epoch 62/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6287 - accuracy: 0.6466 - val_loss: 0.5848 - val_accuracy: 0.6688
Epoch 63/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6190 - accuracy: 0.6466 - val_loss: 0.5817 - val_accuracy: 0.6688
Epoch 64/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6205 - accuracy: 0.6466 - val_loss: 0.5795 - val_accuracy: 0.6688
Epoch 65/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6189 - accuracy: 0.6466 - val_loss: 0.5772 - val_accuracy: 0.6688
Epoch 66/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6155 - accuracy: 0.6466 - val_loss: 0.5743 - val_accuracy: 0.6688
Epoch 67/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6225 - accuracy: 0.6466 - val_loss: 0.5727 - val_accuracy: 0.6688
Epoch 68/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6207 - accuracy: 0.6466 - val_loss: 0.5708 - val_accuracy: 0.6688
Epoch 69/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6116 - accuracy: 0.6466 - val_loss: 0.5685 - val_accuracy: 0.6688
Epoch 70/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6145 - accuracy: 0.6466 - val_loss: 0.5658 - val_accuracy: 0.6688
Epoch 71/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6061 - accuracy: 0.6466 - val_loss: 0.5624 - val_accuracy: 0.6688
Epoch 72/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6056 - accuracy: 0.6466 - val_loss: 0.5598 - val_accuracy: 0.6688
Epoch 73/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6129 - accuracy: 0.6466 - val_loss: 0.5572 - val_accuracy: 0.6688
Epoch 74/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6013 - accuracy: 0.6466 - val_loss: 0.5523 - val_accuracy: 0.6688
Epoch 75/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6054 - accuracy: 0.6466 - val_loss: 0.5498 - val_accuracy: 0.6688
Epoch 76/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5909 - accuracy: 0.6466 - val_loss: 0.5456 - val_accuracy: 0.6688
Epoch 77/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5938 - accuracy: 0.6466 - val_loss: 0.5445 - val_accuracy: 0.6688
Epoch 78/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6001 - accuracy: 0.6466 - val_loss: 0.5414 - val_accuracy: 0.6688
Epoch 79/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6188 - accuracy: 0.6466 - val_loss: 0.5426 - val_accuracy: 0.6688
Epoch 80/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6095 - accuracy: 0.6466 - val_loss: 0.5413 - val_accuracy: 0.6688
Epoch 81/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5915 - accuracy: 0.6466 - val_loss: 0.5387 - val_accuracy: 0.6688
Epoch 82/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5910 - accuracy: 0.6466 - val_loss: 0.5379 - val_accuracy: 0.6688
Epoch 83/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5850 - accuracy: 0.6466 - val_loss: 0.5313 - val_accuracy: 0.6688
Epoch 84/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5883 - accuracy: 0.6466 - val_loss: 0.5276 - val_accuracy: 0.6688
Epoch 85/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6051 - accuracy: 0.6466 - val_loss: 0.5283 - val_accuracy: 0.6688
Epoch 86/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5991 - accuracy: 0.6466 - val_loss: 0.5273 - val_accuracy: 0.6688
Epoch 87/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5829 - accuracy: 0.6466 - val_loss: 0.5263 - val_accuracy: 0.6688
Epoch 88/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5856 - accuracy: 0.6466 - val_loss: 0.5230 - val_accuracy: 0.6688
Epoch 89/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5945 - accuracy: 0.6466 - val_loss: 0.5219 - val_accuracy: 0.6688
Epoch 90/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5898 - accuracy: 0.6466 - val_loss: 0.5188 - val_accuracy: 0.6688
Epoch 91/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5795 - accuracy: 0.6466 - val_loss: 0.5190 - val_accuracy: 0.6688
Epoch 92/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5883 - accuracy: 0.6466 - val_loss: 0.5177 - val_accuracy: 0.6688
Epoch 93/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5798 - accuracy: 0.6466 - val_loss: 0.5162 - val_accuracy: 0.6688
Epoch 94/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5876 - accuracy: 0.6466 - val_loss: 0.5151 - val_accuracy: 0.6688
Epoch 95/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5884 - accuracy: 0.6466 - val_loss: 0.5134 - val_accuracy: 0.6688
Epoch 96/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5733 - accuracy: 0.6466 - val_loss: 0.5110 - val_accuracy: 0.6688
Epoch 97/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5715 - accuracy: 0.6466 - val_loss: 0.5095 - val_accuracy: 0.6688
Epoch 98/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5824 - accuracy: 0.6466 - val_loss: 0.5092 - val_accuracy: 0.6688
Epoch 99/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5680 - accuracy: 0.6466 - val_loss: 0.5079 - val_accuracy: 0.6688
Epoch 100/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5795 - accuracy: 0.6466 - val_loss: 0.5073 - val_accuracy: 0.6688